development:
  adapter: postgresql
  encoding: unicode
  database: Development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: kyle
  password: cs305

production:
  adapter: postgresql
  encoding: unicode
  database: dbijhe4vct3g42
  pool: 5
  username: fyfsoqnvtqcene
  password: LrFqFXYKfQzCSO-OmKyJsDQZ48
